# Generated by Django 6.0.1 on 2026-04-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_blogpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('group', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=160)),
                ('value', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group', 'sort_order', 'label'],
            },
        ),
    ]
