# Generated by Django 6.0.1 on 2026-04-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_sitesnippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('group', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=160)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('fallback_static', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group', 'sort_order', 'label'],
            },
        ),
    ]
